### ISSUE TITLE
(wishlist) Tutorial on how to write extensions in C++

### ISSUE THREAD

**Issue by jpellegrini** [leftmike/foment#31]
I see that, for example, hash tables are implemented as C++ code in `hashtbl.cpp`. For those willing to contribute new code (extensions, etc), it would be nice to have a tutorial on how to write Foment libraries in C++.

One extension I think would be quite useful is SRFI-98, access to environment variables, for example -- but currently, there is no document that helps me start (I'd have to go into the code and understand one of the implemented features).

(How do I use `Define`? What data types I need to use, what is an `FObject`, etc)

**Comment by leftmike** [comment]
It turns out that SRFI-98 is already supported by R7RS Scheme in the process context library.

The source code lives in `foment/src/foment.cpp`: search for `get-environment-variable`. It is defined in the `(scheme process-context)` library in `foment/src/base.scm`.

To define the SRFI library, you could do something like the following (I have not actually run the code though):
```
(define-library (srfi 98)
     (import (foment base))
     (export
         get-environment-variable
         get-environment-variables))
```

But that is not what you are asking for. I am happy to write a tutorial / documentation on how to create an extension.

**Comment by leftmike** [comment]
I have been working on a tutorial / documentation on how to [extend foment](https://github.com/leftmike/foment/wiki/ExtendingFoment); I am not yet done with it.

**Comment by leftmike** [comment]
Done with a first version. Please take a [look](https://github.com/leftmike/foment/wiki/ExtendingFoment) and let me know what you think.

**Comment by jpellegrini** [comment]
Thank you!!! Foment Scheme just became better with that documentation.
